name: tourism_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  http: ^1.2.1
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0
  hydrated_bloc: ^9.1.4
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
